service: git-workflows
frameworkVersion: '2 || 3'
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
provider:
  name: aws
  runtime: nodejs16.x
  # profile: rafae
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: dev

functions:
  sendDataFunction:
    handler: functions/sendData.handler

custom:
  webpack:
   includeModules: true
   webpackConfig: webpack.config.ts
   packager: npm